### PR TITLE
Priority Scheduler

### PR DESCRIPTION
**Pull request by luigisoares97**
Updated the scheduling algorithm to consider other fields than counter (priority and nice):

- Added a macro to calculate the process' effective priority (priority + nice - counter).

- Added a macro to verify whether or not we should update the next process to be executed.

### CODE REVIEW

**Comment by ppenna** [comment]
@Theldus actually me and @luigisoares97 found a bug on the priority scheduling test. In summary, we are writing to the HDD device which no longer exist in the dev branch. @luigisoares97 is working on the fix for that also.

**Comment by Theldus** [comment]
Oh, I got it
You mean the `work_io()` function, right? which tries to read from /dev/hdd... which should not even exist in the dev branch.

**Comment by ppenna** [comment]
Exactly that! We are working some fixed for that =) may I merge it?

**Comment by Theldus** [comment]
Merged ;-)

**Pull request merged**
