### PR TITLE
Add Check Before Switching to New Process

### PR DESCRIPTION
**Pull request by RamAddict**
# Description

This change prevents any unneeded context switch by checking if the current process is equal to next.

### CODE REVIEW

**Comment by ppenna** [comment]
@mbcastro it works fine in Linux, does it in MacOS? I would say that this improvement is OK....

**Comment by mbcastro** [comment]
Considering the default scheduler (round-robin), I think that the `current` process will always be different to the `next` one. This is due to the fact that there will be, at least, 2 processes in the system (`idle` and `init`). Thus, I believe that this pull request wouldn't take any effect.

**Comment by ppenna** [comment]
@mbcastro I agree with you. However, this is a potential enhancement when Nanvix features another scheduler. What do you think? Should we merge it?

**Comment by mbcastro** [comment]
I've just checked this situation with @RamAddict and we found out that the same process can be rescheduled several times in a row. For instance, the `IDLE` process can be rescheduled several times when all other processes are not in `PROC_READY` state. In this case, we don't need to call `switch_to(next)`. So, this pull request makes sense and I'm accepting it. thanks @RamAddict!

**Pull request merged**
